meta:
  engine: 4.1.0
  version: 0.0.1
  author: Henri Nurmi
units:
  $default_width: cx-1
  $default_height: cy-1
  $default_spread: cx
  $default_padding: cy
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
  index_stagger: -8.7
  arch_top_shift: 54
  arch_top_radius: 70
  arch_bottom_shift: 298.5
  arch_bottom_radius: 300
  arch_left_x: 290
  arch_left_y: 0
  arch_left_radius: 302
  arch_right_x: -200
  arch_right_y: 20
  arch_right_radius: 300
  conn_cut_w: 50
  conn_cut_h: 50
  mounting_spacer_diameter: 3.1
  mounting_hole_diameter: 2.2
  mounting_hole_case_inner_diameter: 3
  mounting_hole_case_outer_diameter: 5
  puck_diam: 41.1
  puck_hole_dist: 38.1
  puck_height: 6.6
  puck_post_height: 2.6
  puck_post_length: 2.4
  puck_hole_diam: mounting_hole_diameter
  case_thickness: 1
  case_wall_height: 8
  case_wall_thickness: 2
  case_screw_standoff_height: 4
  
  reset_w: 3.5
  reset_h: 6
  trrs_w: 12 # footprint size, extra mm for circle end
  trrs_h: 6
  mcu_w: 18
  mcu_h: 33
points:
  zones:
    matrix:
      key.tags: switch
      columns:
        pinky:
          key.tags: [switch, switch_reversed]
          rows:
            bottom:
              key_net: P6 
            home:
              key_net: P5
            top:
              key_net: P4
        ring:
          key.stagger: 13
          rows:
            bottom:
              key_net: P3
            home:
              key_net: P2
            top:
              key_net: P0
        middle:
          key.stagger: 6.7
          rows:
            bottom:
              key_net: P1
            home:
              key_net: P18
            top:
              key_net: P15
        index:
          key.stagger: index_stagger
          rows:
            bottom:
              key_net: P14
            home:
              key_net: P16
            top:
              key_net: P10
        inner:
          key.stagger: -3.5
          rows:
            bottom:
              key_net: P19
            home:
              key_net: P20
            top:
              key_net: P21
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [50, -100]
    thumbs:
      key.tags: [switch, thumb]
      anchor:
        ref:
          ref: matrix_inner_bottom
          shift: [-kx/2, -ky/2]
          rotate: -10
        shift: [-2, -ky/2]
      columns:
        inner:
          key:
            key_net: P7
        home:
          key:
            # hinge at bottom-left corner of key
            origin: [-kx/2, -ky/2]
            splay: -8
            key_net: P8
        outer:
          key:
            # hinge at bottom-left corner of key
            origin: [-kx/2, -ky/2]
            splay: -8
            key_net: P9
      rows:
        cluster:

    puck_left:
      key.tags: puck_hole
      anchor:
        ref: matrix_middle_home
        shift: [-kx/2 - 1, -7]
      columns: {x:}
      rows: {y:}
    puck_center:
      anchor:
        ref: puck_left_x_y
        shift: [puck_hole_dist/2, 0]
      columns: {x:}
      rows: {y:}
    puck_top:
      key.tags: puck_hole
      anchor:
        ref: puck_center_x_y
        shift: [0, puck_hole_dist/2]
      columns: {x:}
      rows: {y:}
    puck_right:
      key.tags: puck_hole
      anchor:
        ref: puck_center_x_y
        shift: [puck_hole_dist/2, 0]
      columns: {x:}
      rows: {y:}
    puck_bottom:
      key.tags: puck_hole
      anchor:
        ref: puck_center_x_y
        shift: [0, -puck_hole_dist/2]
      columns: {x:}
      rows: {y:}

    reset:
      anchor:
        ref: matrix_inner_bottom
        shift: [kx/2 + reset_w/2, -ky/2 - 4 + reset_h/2]
      columns: {x:}
      rows: {y:}
    trrs:
      anchor:
        ref:  reset_x_y
        shift: [reset_w/2 + .5 + trrs_w/2, 0]
      columns: {x:}
      rows: {y:}
    mcu:
      anchor:
        ref: reset_x_y
        shift: [-reset_w/2 + mcu_w / 2, trrs_h / 2 + mcu_h/2 + .5]
      columns: {x:}
      rows: {y:}

    mounting_left:
      key:
        tags: mount
        padding: 2ky
      anchor:
        ref: matrix_pinky_bottom
        shift: [kx/2, ky/2]
      columns: { x1: }
      rows: { y1:, y2: }
    mounting_right:
      key:
        tags: mount
        padding: 3ky
      anchor:
        ref: matrix_inner_bottom
        shift: [-kx/2, -ky/2]
      columns: { x1: }
      rows: { y1:, y2: }
    mounting_thumb:
      key:
        tags: mount
      anchor:
        ref: thumbs_outer_cluster
        shift: [-kx/2 - 2, ky/2 + 2]
      columns: { x: }
      rows: { y: }

outlines:
  keys:
    - what: rectangle
      where: [switch]
      size: [kx-1, ky-1]
  _thumbs:
    - what: rectangle
      where: [thumb]
      size: [kx, ky]
  # MCU
  _mcu:
    - what: rectangle
      size: [mcu_w, mcu_h]
      where: mcu_x_y
  _conn_cut_left:
    - what: rectangle
      size: [conn_cut_w, conn_cut_h]
      where:
        ref: mcu_x_y
        shift: [-mcu_w/2 + conn_cut_w/2, mcu_h/2 + conn_cut_h/2]
  # todo misnamed, above is to cut space above mcu, this is to cut mcu
  _conn_cut_left_poly:
    - what: polygon
      points:
        - ref: mcu_x_y
          shift: [-mcu_w/2, mcu_h/2 + 5]
        - ref: reset_x_y
          shift: [-reset_w/2, -reset_h/2]
        - ref: trrs_x_y
          shift: [trrs_w/2 + 5, -trrs_h/2]
        - ref: mcu_x_y
          shift: [mcu_w/2, mcu_h/2]
  _reset:
    - what: rectangle
      size: [reset_w, reset_h]
      where: reset_x_y
  _trrs:
    - what: rectangle
      size: [trrs_w, trrs_h]
      where: trrs_x_y
  # Mounting holes
  _mounting_holes:
    - what: circle
      radius: mounting_hole_diameter/2
      where: mount
  _mounting_holes_case:
    - what: circle
      radius: mounting_hole_case_outer_diameter/2
      where: mount
    - what: circle
      radius: mounting_hole_case_inner_diameter/2
      where: mount
      operation: subtract
  _puck_holes:
    - what: circle
      radius: puck_hole_diam/2
      where: puck_hole
  _puck_case_hole:
    - what: circle
      radius: puck_diam/2
      where: puck_center_x_y
  # Board outlines
  board_left_poly:
    - what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [-kx/2, ky/2]
        - ref: matrix_ring_top
          shift: [-kx/2, ky/2]
        - ref: matrix_middle_top
          shift: [-kx/2, ky/2]
        - ref: matrix_middle_top
          shift: [kx/2, ky/2]
        - ref: matrix_index_top
          shift: [kx/2, ky/2]
        - ref: matrix_inner_top
          shift: [kx/2, ky/2]
        - ref: mcu_x_y
          shift: [-mcu_w/2, mcu_h/2]
        - ref: mcu_x_y
          shift: [mcu_w/2, mcu_h/2]
        - ref: mcu_x_y
          shift: [mcu_w/2, -mcu_h/2 - trrs_h - 5]
        - ref: thumbs_outer_cluster
          shift: [kx/2, ky/2]
        - ref: thumbs_outer_cluster
          shift: [kx/2, -ky/2]
        - ref: thumbs_home_cluster
          shift: [kx/2, -ky/2]
        - ref: thumbs_inner_cluster
          shift: [kx/2, -ky/2]
        - ref: thumbs_inner_cluster
          shift: [-kx/2, -ky/2]
        - ref: matrix_pinky_bottom
          shift: [kx/2, -ky/2]
        - ref: matrix_pinky_bottom
          shift: [-kx/2, -ky/2]
    - what: outline
      name: board_left_poly
      fillet: 2
  board_left_poly_expanded:
    - what: outline
      name: board_left_poly
      expand: case_wall_thickness
  board_left_only_expanded:
    [board_left_poly_expanded, -board_left_poly]
  board_left:
    [ board_left_poly,-_conn_cut_left, -_mounting_holes, -_puck_holes]
  board_pcb_left:
    [ board_left_poly]#,-_conn_cut_left]
  # Switch plate
  _switch_cutouts:
    - what: rectangle
      where: [switch]
      asym: source
      size: 14
      bound: false
  switch_plate:
    [board_left_poly, -_switch_cutouts, -_conn_cut_left_poly]
  switch_plate_with_mounting:
    [switch_plate, -_mounting_holes]
  # Debug outlines
  _debug:
   #- name: board_pcb_left
    - name: board_left_poly
    - operation: stack
      name: keys
  _debug2:
    - name: _trrs
    - operation: stack
      name: _debug
  _debug3:
    - name: _mcu
    - operation: stack
      name: _debug2
  _debug4:
    - name: _reset
    - operation: stack
      name: _debug3
  _debug5:
    - name: _puck_holes
    - operation: stack
      name: _debug4
  debug:
    - name: _mounting_holes
    - operation: stack
      name: _debug5
pcbs:
  board:
    template: kicad8
    outlines:
      main:
        outline: board_pcb_left
    footprints:
      switch:
        what: ceoloide/switch_choc_v1_v2 #choc
        where: [[-/^mirror_.*/, switch, -switch_reversed]]
        adjust:
          rotate: 180
        params:
          from: "{{key_net}}"
          to: GND
          hotswap: true
          include_keycap: true
          choc_v2_support: false
      switch_reversed:
        what: ceoloide/switch_choc_v1_v2 #choc
        where: [[-/^mirror_.*/, switch_reversed]]
        params:
          from: "{{key_net}}"
          to: GND
          hotswap: true
          include_keycap: true
          choc_v2_support: false
          #keycaps: true
      promicro:
        #what: promicro_custom
        what: ceoloide/mcu_supermini_nrf52840
        where:
          ref: mcu_x_y #mcu_pt_c_r
          #rotate: -90
        params:
          reverse_mount: true
          only_required_jumpers: true
        #  orientation: down
      trrs:
        what: ceoloide/trrs_pj320a
        where:
          ref: trrs_x_y #reset_ttrs_pt_trrs_r
          shift: [trrs_w/2, 0]
          rotate: -90
        #params:
        #  A: VCC
        #  B: DATA
        #  C: GND
        #  D: ''
      reset:
        what: ceoloide/reset_switch_tht_top
        where:
          ref: reset_x_y #reset_ttrs_pt_reset_r
          rotate: -90
      test_mount_point:
        what: mounting_hole_plated
        where: reset_ttrs_pt_reset_r
        params.drill: 1
      zone_front:
        what: zone
        where:
          ref: matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: VCC
          side: F
          width: 8.5kx
          height: 6.5ky
      zone_back:
        what: zone
        where:
          ref: matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: GND
          side: B
          width: 8.5kx
          height: 6.5ky
      mounting:
        what: mounting_hole_plated
        where: [[-/^mirror_.*/, mount]]
        params.drill: mounting_spacer_diameter
      puck_mounting:
        what: mounting_hole_plated
        where: [[-/^mirror_.*/, puck_hole]]
        params.drill: puck_hole_diam

  top_plate:
    template: kicad8
    outlines:
      main:
        outline: switch_plate
    footprints:
      mounting:
        what: mounting_hole_npth
        where: [[-/^mirror_.*/, mount]]
        params.hole_size: mounting_hole_diameter
        params.hole_drill: mounting_hole_diameter
cases:
    _bottom:
      - what: outline
        name: board_left_poly_expanded
        extrude: case_thickness
    _wall:
      - what: outline
        name: board_left_only_expanded
        extrude: case_wall_height
    _mounting_holes:
      - what: outline
        name: _mounting_holes_case
        extrude: case_screw_standoff_height
    mycase:
      - what: case
        name: _bottom
      - what: case
        name: _wall    
      - what: case
        name: _mounting_holes
      - what: outline
        name: _puck_case_hole
        extrude: case_thickness
        operation: subtract
        
